export const courtSyncSources = [
  {
    key: 'livelaw_rss',
    name: 'LiveLaw Latest Legal News',
    sourceType: 'legal_news_feed',
    jurisdiction: { country: 'India', court: null, level: 'legal_news', state: null },
    documentType: 'legal_news',
    url: 'https://www.livelaw.in/google_feeds.xml',
    strategy: 'rss_xml',
    enabled: true,
    recommendedForScraping: true,
    tags: ['legal-news', 'courts', 'india'],
  },
  {
    key: 'sci_latest_orders',
    name: 'Supreme Court Latest Orders',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: 'Supreme Court of India', level: 'supreme_court', state: null },
    documentType: 'court_order',
    url: 'https://www.sci.gov.in/latest-orders/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['supreme-court', 'latest-orders'],
  },
  {
    key: 'sci_notices_circulars',
    name: 'Supreme Court Notices and Circulars',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: 'Supreme Court of India', level: 'supreme_court', state: null },
    documentType: 'notice',
    url: 'https://www.sci.gov.in/notices-and-circulars/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['supreme-court', 'notices', 'circulars'],
  },
  {
    key: 'sci_press_releases',
    name: 'Supreme Court Press Releases',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: 'Supreme Court of India', level: 'supreme_court', state: null },
    documentType: 'press_release',
    url: 'https://www.sci.gov.in/press-release/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['supreme-court', 'press-release'],
  },
  {
    key: 'sci_collegium_resolutions',
    name: 'Supreme Court Collegium Resolutions',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: 'Supreme Court of India', level: 'supreme_court', state: null },
    documentType: 'collegium_resolution',
    url: 'https://www.sci.gov.in/collegium-resolutions/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['supreme-court', 'collegium'],
  },
  {
    key: 'egazette',
    name: 'eGazette of India',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'gazette', state: null },
    documentType: 'gazette',
    url: 'https://egazette.gov.in/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['gazette', 'laws', 'notifications', 'amendments'],
  },
  {
    key: 'lawmin_notifications',
    name: 'Ministry of Law and Justice Notifications',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'ministry', state: null },
    documentType: 'notification',
    url: 'https://lawmin.gov.in/notification',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['law-ministry', 'notification'],
  },
  {
    key: 'lawmin_acts_rules',
    name: 'Ministry of Law and Justice Acts and Rules',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'ministry', state: null },
    documentType: 'act_or_rule',
    url: 'https://lawmin.gov.in/acts-rules',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['law-ministry', 'acts', 'rules'],
  },
  {
    key: 'legislative_amendment_acts',
    name: 'Legislative Department Amendment Acts',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'legislative_department', state: null },
    documentType: 'amendment_act',
    url: 'https://www.legislative.gov.in/document-category/amendment-acts',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['legislative', 'amendment-act'],
  },
  {
    key: 'legislative_central_acts',
    name: 'Legislative Department Central Acts',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'legislative_department', state: null },
    documentType: 'act',
    url: 'https://legislative.gov.in/document-category/list-of-central-acts/',
    strategy: 'html_pdf_links',
    enabled: true,
    recommendedForScraping: true,
    tags: ['legislative', 'central-act'],
  },
  {
    key: 'hcservices_ecourts',
    name: 'High Court Services eCourts',
    sourceType: 'official_website',
    jurisdiction: { country: 'India', court: null, level: 'high_court', state: null },
    documentType: 'case_lookup',
    url: 'https://hcservices.ecourts.gov.in/',
    strategy: 'user_triggered_lookup_only',
    enabled: false,
    recommendedForScraping: false,
    reason: 'CAPTCHA/session-based; avoid mass scraping.',
    tags: ['ecourts', 'high-court'],
  },
];
