import {
  Activity,
  Archive,
  BarChart3,
  Bell,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  CheckSquare,
  CircleDollarSign,
  ClipboardList,
  Clock3,
  CloudOff,
  CreditCard,
  DatabaseBackup,
  FileClock,
  FileText,
  Gavel,
  Gauge,
  HelpCircle,
  History,
  Inbox,
  Landmark,
  LayoutDashboard,
  Lock,
  Mail,
  MessageCircle,
  NotebookTabs,
  Plug,
  ReceiptText,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Smartphone,
  Timer,
  UploadCloud,
  UserCog,
  UserRound,
  Users,
  WalletCards,
  WifiOff,
} from "lucide-react";

export const navigationItems = [
  { label: "Dashboard", path: "/app/dashboard", icon: LayoutDashboard, moduleKey: "dashboard" },
  { label: "My Profile", path: "/app/profile", icon: UserRound, moduleKey: "dashboard" },
  { label: "Clients", path: "/app/clients", icon: Users, moduleKey: "clients" },
  { label: "Matters", path: "/app/matters", icon: BriefcaseBusiness, moduleKey: "matters" },
  { label: "Tasks", path: "/app/tasks", icon: CheckSquare, moduleKey: "tasks" },
  { label: "Work Meter", path: "/app/work-meter", icon: Timer, moduleKey: "work" },
  { label: "Submit Work", path: "/app/submit-work", icon: CheckCircle2, moduleKey: "work" },
  { label: "Approve Work", path: "/app/time-approval", icon: ShieldCheck, moduleKey: "approval" },
  { label: "Time Entries", path: "/app/time-entries", icon: FileClock, moduleKey: "work" },
  { label: "Captured Work", path: "/app/captured-work", icon: Inbox, moduleKey: "work" },
  { label: "Court Sync", path: "/app/court-sync", icon: Gavel, moduleKey: "work" },
  { label: "Communications", path: "/app/communications", icon: MessageCircle, moduleKey: "clients" },
  { label: "Billing", path: "/app/billables", icon: CircleDollarSign, moduleKey: "billing" },
  { label: "Finance", path: "/app/finance", icon: BarChart3, moduleKey: "finance" },
  { label: "People", path: "/app/hr", icon: Users, moduleKey: "people" },
  { label: "Assistant", path: "/app/assistant", icon: Bot, moduleKey: "assistant" },
  { label: "Settings", path: "/app/settings", icon: Settings, moduleKey: "settings" },
];

export const appRoutes = [
  { path: "/app/dashboard", title: "Dashboard", module: "Daily Work", moduleKey: "dashboard", roleGroup: "All roles", icon: Gauge },
  { path: "/app/profile", title: "My Profile", module: "Workspace", moduleKey: "dashboard", roleGroup: "All roles", icon: UserRound },
  { path: "/app/setup-status", title: "My Setup Status", module: "Onboarding", moduleKey: "extension", roleGroup: "All roles", icon: Plug },
  { path: "/app/notifications", title: "Notifications", module: "Workspace", moduleKey: "dashboard", roleGroup: "All roles", icon: Bell },
  { path: "/app/search", title: "Global Search", module: "Workspace", moduleKey: "dashboard", roleGroup: "All roles", icon: Search },
  { path: "/app/help", title: "Help Center", module: "Support", moduleKey: "support", roleGroup: "All roles", icon: HelpCircle },
  { path: "/app/clients", title: "Client List", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Users },
  { path: "/app/clients/new", title: "Create Client", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Users },
  { path: "/app/clients/:clientId", title: "Client Detail", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Users },
  { path: "/app/clients/:clientId/edit", title: "Edit Client", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Users },
  { path: "/app/clients/:clientId/contacts", title: "Client Contacts", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Users },
  { path: "/app/clients/:clientId/billing", title: "Client Billing Summary", module: "Clients", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: CircleDollarSign },
  { path: "/app/matters", title: "Matter List", module: "Matters", moduleKey: "matters", roleGroup: "All legal roles", icon: BriefcaseBusiness },
  { path: "/app/matters/new", title: "Create Matter", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner, Lawyer", icon: BriefcaseBusiness },
  { path: "/app/matters/:matterId", title: "Matter Detail", module: "Matters", moduleKey: "matters", roleGroup: "All legal roles", icon: BriefcaseBusiness },
  { path: "/app/matters/:matterId/edit", title: "Edit Matter", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner, Lawyer", icon: BriefcaseBusiness },
  { path: "/app/matters/:matterId/overview", title: "Matter Overview", module: "Matters", moduleKey: "matters", roleGroup: "All legal roles", icon: NotebookTabs },
  { path: "/app/matters/:matterId/team", title: "Matter Team", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner, Lawyer", icon: UserCog },
  { path: "/app/matters/:matterId/timeline", title: "Matter Timeline", module: "Matters", moduleKey: "matters", roleGroup: "All legal roles", icon: History },
  { path: "/app/matters/:matterId/documents", title: "Matter Documents", module: "Matters", moduleKey: "matters", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/matters/:matterId/billing", title: "Matter Billing", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner, Lawyer", icon: ReceiptText },
  { path: "/app/matters/:matterId/audit", title: "Matter Audit Trail", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner", icon: ShieldCheck },
  { path: "/app/case-assignments", title: "Matter Assignments", module: "Matters", moduleKey: "matters", roleGroup: "Admin, Partner", icon: UserCog },
  { path: "/app/tasks", title: "My Tasks", module: "Tasks", moduleKey: "tasks", roleGroup: "All roles", icon: CheckSquare },
  { path: "/app/tasks/board", title: "Team Task Board", module: "Tasks", moduleKey: "tasks", roleGroup: "Admin, Partner, Lawyer", icon: ClipboardList },
  { path: "/app/tasks/new", title: "Create Task", module: "Tasks", moduleKey: "tasks", roleGroup: "Admin, Partner, Lawyer", icon: CheckSquare },
  { path: "/app/tasks/:taskId", title: "Task Detail", module: "Tasks", moduleKey: "tasks", roleGroup: "All roles", icon: CheckSquare },
  { path: "/app/tasks/:taskId/edit", title: "Edit Task", module: "Tasks", moduleKey: "tasks", roleGroup: "Admin, Partner, Lawyer", icon: CheckSquare },
  { path: "/app/my-work-today", title: "My Work Today", module: "Tasks", moduleKey: "tasks", roleGroup: "All roles", icon: Clock3 },
  { path: "/app/work-meter", title: "Work Meter", module: "Time Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Timer },
  { path: "/app/work-sessions", title: "Work Session History", module: "Time Capture", moduleKey: "work", roleGroup: "All legal roles", icon: FileClock },
  { path: "/app/time-entry/new", title: "Manual Time Entry", module: "Time Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Timer },
  { path: "/app/time-entries", title: "Time Entries", module: "Time Capture", moduleKey: "work", roleGroup: "All legal roles", icon: FileClock },
  { path: "/app/time-approval", title: "Approve Submitted Work", module: "Time Capture", moduleKey: "approval", roleGroup: "Admin, Partner", icon: ShieldCheck },
  { path: "/app/captured-work", title: "Captured Work Review", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Inbox },
  { path: "/app/submit-work", title: "Submit Work for Approval", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: CheckCircle2 },
  { path: "/app/gmail-review", title: "Gmail Capture Review", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Mail },
  { path: "/app/research-review", title: "Research Capture Review", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Search },
  { path: "/app/activities", title: "Activity Capture", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Activity },
  { path: "/app/email-entries", title: "Email Entries", module: "Capture", moduleKey: "work", roleGroup: "All legal roles", icon: Mail },
  { path: "/app/communications", title: "Communication Center", module: "Communications", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: MessageCircle },
  { path: "/app/communications/whatsapp", title: "WhatsApp Inbox", module: "Communications", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: MessageCircle },
  { path: "/app/communications/sms", title: "SMS Center", module: "Communications", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Smartphone },
  { path: "/app/communications/logs", title: "Communication Logs", module: "Communications", moduleKey: "clients", roleGroup: "Admin, Partner, Lawyer", icon: Mail },
  { path: "/app/billables", title: "Billables", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner, Lawyer, Associate", icon: CircleDollarSign },
  { path: "/app/billables/:billableId", title: "Billable Detail", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner, Lawyer, Associate", icon: CircleDollarSign },
  { path: "/app/billables/approval", title: "Billable Approval Queue", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: CheckCircle2 },
  { path: "/app/rate-cards", title: "Rate Cards", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: Landmark },
  { path: "/app/invoices", title: "Invoices", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/invoices/new", title: "Invoice Builder", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/invoices/:invoiceId", title: "Invoice Detail", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/invoices/:invoiceId/lines", title: "Invoice Lines", module: "Billing", moduleKey: "billing", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/payments", title: "Payments", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: CreditCard },
  { path: "/app/reconciliation", title: "Payment Reconciliation", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: WalletCards },
  { path: "/app/ar-aging", title: "Receivables Aging", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: WalletCards },
  { path: "/app/revenue", title: "Revenue", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: BarChart3 },
  { path: "/app/kpi", title: "KPI Summary", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: BarChart3 },
  { path: "/app/kpi-snapshots", title: "KPI Snapshots", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: Archive },
  { path: "/app/analytics", title: "Analytics", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: BarChart3 },
  { path: "/app/reports", title: "Reports", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: FileText },
  { path: "/app/finance", title: "Finance Dashboard", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: BarChart3 },
  { path: "/app/gst", title: "GST Dashboard", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/tds", title: "TDS Management", module: "Finance", moduleKey: "finance", roleGroup: "Admin, Partner", icon: Landmark },
  { path: "/app/hr", title: "HR Dashboard", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: Users },
  { path: "/app/people", title: "Team Directory", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: Users },
  { path: "/app/people/:userId", title: "Employee Profile", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: UserRound },
  { path: "/app/workload", title: "Workload Overview", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: Gauge },
  { path: "/app/attendance", title: "Attendance and Leave", module: "People", moduleKey: "dashboard", roleGroup: "All roles", icon: Clock3 },
  { path: "/app/workforce-analytics", title: "Workforce Analytics", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: BarChart3 },
  { path: "/app/payroll", title: "Payroll Runs", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: WalletCards },
  { path: "/app/payroll/:runId", title: "Payroll Detail", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: FileText },
  { path: "/app/compensation", title: "Compensation Setup", module: "People", moduleKey: "people", roleGroup: "Admin, Partner", icon: CircleDollarSign },
  { path: "/app/calendar", title: "Calendar and Hearings", module: "Calendar", moduleKey: "work", roleGroup: "All legal roles", icon: CalendarDays },
  { path: "/app/hearings", title: "Hearing Dashboard", module: "Calendar", moduleKey: "work", roleGroup: "All legal roles", icon: CalendarDays },
  { path: "/app/hearings/manual-time", title: "Court Time Entry", module: "Calendar", moduleKey: "work", roleGroup: "All legal roles", icon: CalendarDays },
  { path: "/app/court-sync", title: "Court Daily Sync", module: "Court Sync", moduleKey: "work", roleGroup: "All legal roles", icon: Gavel },
  { path: "/app/court-sync/matches", title: "Court Case Match", module: "Court Sync", moduleKey: "work", roleGroup: "All legal roles", icon: Gavel },
  { path: "/app/court-sync/verdicts/:verdictId", title: "Verdict Detail", module: "Court Sync", moduleKey: "work", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/court-sync/settings", title: "Court Sync Settings", module: "Court Sync", moduleKey: "work", roleGroup: "Admin, Partner", icon: Settings },
  { path: "/app/document-storage", title: "Document Storage", module: "Documents", moduleKey: "matters", roleGroup: "All legal roles", icon: DatabaseBackup },
  { path: "/app/document-storage/upload", title: "Upload Document", module: "Documents", moduleKey: "matters", roleGroup: "All legal roles", icon: UploadCloud },
  { path: "/app/document-storage/:documentId", title: "Document Viewer", module: "Documents", moduleKey: "matters", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/storage-settings", title: "Storage Settings", module: "Documents", moduleKey: "matters", roleGroup: "Admin, Partner", icon: Settings },
  { path: "/app/recordings", title: "Recording Library", module: "Meetings", moduleKey: "work", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/recordings/:recordingId", title: "Recording Detail", module: "Meetings", moduleKey: "work", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/assistant", title: "AI Assistant", module: "Assistant", moduleKey: "assistant", roleGroup: "All roles", icon: Bot },
  { path: "/app/assistant/email", title: "AI Email Writer", module: "Assistant", moduleKey: "assistant", roleGroup: "All roles", icon: Mail },
  { path: "/app/assistant/research", title: "AI Research Assistant", module: "Assistant", moduleKey: "assistant", roleGroup: "All legal roles", icon: Search },
  { path: "/app/assistant/documents", title: "Document Summary", module: "Assistant", moduleKey: "assistant", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/assistant/documents/create", title: "Document Creation", module: "Assistant", moduleKey: "assistant", roleGroup: "All legal roles", icon: FileText },
  { path: "/app/assistant/documents/qa", title: "Matter Document Q&A", module: "Assistant", moduleKey: "assistant", roleGroup: "All legal roles", icon: Bot },
  { path: "/app/assistant/extension", title: "Extension Coach", module: "Assistant", moduleKey: "assistant", roleGroup: "All roles", icon: Sparkles },
  { path: "/app/assistant/work-meter", title: "Work Meter Coach", module: "Assistant", moduleKey: "assistant", roleGroup: "All roles", icon: Sparkles },
  { path: "/app/assistant/matter-summary", title: "Matter Summary", module: "Assistant", moduleKey: "assistant", roleGroup: "All legal roles", icon: Sparkles },
  { path: "/app/extension/setup", title: "Extension Setup", module: "Extension", moduleKey: "extension", roleGroup: "All roles", icon: Plug },
  { path: "/app/extension/status", title: "Extension Status", module: "Extension", moduleKey: "extension", roleGroup: "All roles", icon: Plug },
  { path: "/app/extension/troubleshooting", title: "Extension Troubleshooting", module: "Extension", moduleKey: "extension", roleGroup: "All roles", icon: Plug },
  { path: "/app/integrations", title: "Integrations", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: Settings },
  { path: "/app/integrations/cloud-storage", title: "Cloud Storage Providers", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: DatabaseBackup },
  { path: "/app/integrations/google-drive", title: "Google Drive Setup", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: DatabaseBackup },
  { path: "/app/integrations/aws-storage", title: "AWS Firm Storage", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: DatabaseBackup },
  { path: "/app/integrations/zoho", title: "Zoho Connection", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: Plug },
  { path: "/app/integrations/zoho/workdrive", title: "Zoho WorkDrive Link", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: DatabaseBackup },
  { path: "/app/integrations/zoho/logs", title: "Zoho Sync Logs", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: History },
  { path: "/app/integration-logs", title: "Integration Logs", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: History },
  { path: "/app/settings", title: "Firm Settings", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: Settings },
  { path: "/app/settings/invoice-tax", title: "Invoice and Tax Defaults", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: ReceiptText },
  { path: "/app/settings/storage-defaults", title: "Storage Defaults", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: DatabaseBackup },
  { path: "/app/settings/notifications", title: "Notification Defaults", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: Bell },
  { path: "/app/security", title: "Security and Access", module: "Settings", moduleKey: "settings", roleGroup: "Admin", icon: Lock },
  { path: "/app/compliance", title: "Compliance Settings", module: "Settings", moduleKey: "settings", roleGroup: "Admin, Partner", icon: ShieldCheck },
  { path: "/app/firms", title: "Firms", module: "Admin", moduleKey: "settings", roleGroup: "Admin", icon: Building2 },
  { path: "/app/admin", title: "Admin Dashboard", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/admin/users", title: "User Management", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/admin/partner-profiles", title: "Partner Profiles", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/admin/lawyer-profiles", title: "Lawyer Profiles", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/admin/associate-profiles", title: "Associate Profiles", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/admin/intern-profiles", title: "Intern Profiles", module: "Admin", moduleKey: "admin", roleGroup: "Admin", icon: UserCog },
  { path: "/app/evidence", title: "Testing Evidence", module: "Support", moduleKey: "support", roleGroup: "Admin, Partner", icon: UploadCloud },
];

export const fallbackRoutes = [
  { path: "/states/loading-workspace", title: "Loading Workspace", module: "Fallback States", icon: Clock3 },
  { path: "/states/empty-dashboard", title: "Empty Dashboard", module: "Fallback States", icon: LayoutDashboard },
  { path: "/states/no-matters-assigned", title: "No Matters Assigned", module: "Fallback States", icon: BriefcaseBusiness },
  { path: "/states/session-expired", title: "Session Expired", module: "Fallback States", icon: Lock },
  { path: "/states/permission-needed", title: "Permission Needed", module: "Fallback States", icon: ShieldAlert },
  { path: "/states/connection-needs-attention", title: "Connection Needs Attention", module: "Fallback States", icon: WifiOff },
  { path: "/states/save-failed", title: "Save Failed", module: "Fallback States", icon: CloudOff },
  { path: "/states/offline", title: "Offline", module: "Fallback States", icon: WifiOff },
  { path: "/states/search-empty", title: "Search Empty", module: "Fallback States", icon: Search },
  { path: "/states/calendar-not-connected", title: "Calendar Not Connected", module: "Fallback States", icon: CalendarDays },
  { path: "/states/payment-failed", title: "Payment Failed", module: "Fallback States", icon: CreditCard },
  { path: "/states/upload-progress", title: "Upload Progress", module: "Fallback States", icon: UploadCloud },
  { path: "/states/assistant-thinking", title: "Assistant Thinking", module: "Fallback States", icon: Bot },
  { path: "/states/extension-connected", title: "Extension Connected", module: "Fallback States", icon: Plug },
  { path: "/states/recorder-permission", title: "Recorder Permission", module: "Fallback States", icon: Lock },
  { path: "/states/report-unavailable", title: "Report Unavailable", module: "Fallback States", icon: FileText },
  { path: "/states/billing-ready", title: "Billing Ready", module: "Fallback States", icon: CheckCircle2 },
  { path: "/states/approval-submitted", title: "Approval Submitted", module: "Fallback States", icon: CheckCircle2 },
  { path: "/states/invite-accepted", title: "Invite Accepted", module: "Fallback States", icon: CheckCircle2 },
  { path: "/states/password-reset", title: "Password Reset", module: "Fallback States", icon: Lock },
  { path: "/states/storage-unavailable", title: "Storage Unavailable", module: "Fallback States", icon: DatabaseBackup },
  { path: "/states/sync-progress", title: "Sync Progress", module: "Fallback States", icon: Activity },
  { path: "/states/no-captured-work", title: "No Captured Work", module: "Fallback States", icon: Inbox },
  { path: "/states/not-configured", title: "Not Configured Yet", module: "Fallback States", icon: Settings },
];

export const allRoutes = [...appRoutes, ...fallbackRoutes];

export function groupedRoutes() {
  return allRoutes.reduce((groups, route) => {
    groups[route.module] = groups[route.module] || [];
    groups[route.module].push(route);
    return groups;
  }, {});
}
