export const fallbackStateCatalog = [
  {
    id: "loading-workspace",
    path: "/states/loading-workspace",
    title: "Loading Workspace",
    kind: "loading",
    group: "Loading",
    message: "We are preparing your workspace and checking the latest firm activity.",
    primaryAction: "Keep waiting",
    secondaryAction: "Back to dashboard",
    animation: "spinner",
  },
  {
    id: "empty-dashboard",
    path: "/states/empty-dashboard",
    title: "Empty Dashboard",
    kind: "empty",
    group: "Empty",
    message: "There is no work to show yet. Start with a matter, task, or captured activity.",
    primaryAction: "Create first matter",
    secondaryAction: "View setup",
  },
  {
    id: "no-matters-assigned",
    path: "/states/no-matters-assigned",
    title: "No Matters Assigned",
    kind: "empty",
    group: "Empty",
    message: "No matters are assigned to you yet. Ask your team lead to add you when work is ready.",
    primaryAction: "Refresh matters",
    secondaryAction: "Open tasks",
  },
  {
    id: "session-expired",
    path: "/states/session-expired",
    title: "Session Expired",
    kind: "permission",
    group: "Access",
    message: "For your firm's safety, please sign in again before continuing.",
    primaryAction: "Sign in again",
    secondaryAction: "Back to home",
  },
  {
    id: "permission-needed",
    path: "/states/permission-needed",
    title: "Permission Needed",
    kind: "permission",
    group: "Access",
    message: "Your current role does not include this area. Your firm administrator can update access if needed.",
    primaryAction: "Request access",
    secondaryAction: "Back to dashboard",
  },
  {
    id: "connection-needs-attention",
    path: "/states/connection-needs-attention",
    title: "Connection Needs Attention",
    kind: "offline",
    group: "Connection",
    message: "BillSync cannot reach this service right now. Your work is safe while we try again.",
    primaryAction: "Try again",
    secondaryAction: "Work offline",
  },
  {
    id: "save-failed",
    path: "/states/save-failed",
    title: "Save Failed",
    kind: "error",
    group: "Recovery",
    message: "Your latest change was not saved. Review the details and try once more.",
    primaryAction: "Retry save",
    secondaryAction: "Keep draft",
  },
  {
    id: "offline",
    path: "/states/offline",
    title: "Offline",
    kind: "offline",
    group: "Connection",
    message: "You appear to be offline. You can review open pages and continue when the connection returns.",
    primaryAction: "Check again",
    secondaryAction: "View saved work",
  },
  {
    id: "search-empty",
    path: "/states/search-empty",
    title: "Search Empty",
    kind: "empty",
    group: "Empty",
    message: "No matching matters, clients, or tasks were found. Try a broader search term.",
    primaryAction: "Clear search",
    secondaryAction: "Browse dashboard",
  },
  {
    id: "calendar-not-connected",
    path: "/states/calendar-not-connected",
    title: "Calendar Not Connected",
    kind: "unavailable",
    group: "Integrations",
    message: "Court dates and hearings will appear here after your calendar is connected.",
    primaryAction: "Connect calendar",
    secondaryAction: "Add time manually",
  },
  {
    id: "payment-failed",
    path: "/states/payment-failed",
    title: "Payment Failed",
    kind: "error",
    group: "Payments",
    message: "The payment could not be completed. No duplicate payment will be made from this screen.",
    primaryAction: "Try payment again",
    secondaryAction: "Review invoice",
    animation: "payment",
  },
  {
    id: "upload-progress",
    path: "/states/upload-progress",
    title: "Upload Progress",
    kind: "loading",
    group: "Files",
    message: "Your document is being uploaded. Keep this page open until it finishes.",
    primaryAction: "View upload details",
    secondaryAction: "Cancel upload",
    animation: "progress",
    progress: 64,
  },
  {
    id: "assistant-thinking",
    path: "/states/assistant-thinking",
    title: "Assistant Thinking",
    kind: "loading",
    group: "Assistant",
    message: "The assistant is reviewing the context. This can take a little longer for larger matters.",
    primaryAction: "Keep waiting",
    secondaryAction: "Ask a shorter question",
    animation: "shimmer",
  },
  {
    id: "extension-connected",
    path: "/states/extension-connected",
    title: "Extension Connected",
    kind: "success",
    group: "Extension",
    message: "The browser extension is connected and ready to help capture work.",
    primaryAction: "Open extension setup",
    secondaryAction: "Test capture",
    animation: "check",
  },
  {
    id: "recorder-permission",
    path: "/states/recorder-permission",
    title: "Recorder Permission",
    kind: "permission",
    group: "Recording",
    message: "Recording needs microphone access before the meeting timer can begin.",
    primaryAction: "Allow microphone",
    secondaryAction: "Use manual notes",
    animation: "waveform",
  },
  {
    id: "report-unavailable",
    path: "/states/report-unavailable",
    title: "Report Unavailable",
    kind: "unavailable",
    group: "Reports",
    message: "This report is not ready yet. You can still review invoices, payments, and matter activity.",
    primaryAction: "Refresh report",
    secondaryAction: "Open finance",
  },
  {
    id: "billing-ready",
    path: "/states/billing-ready",
    title: "Billing Ready",
    kind: "success",
    group: "Billing",
    message: "The selected work is ready for billing review.",
    primaryAction: "Review billables",
    secondaryAction: "Open matter",
  },
  {
    id: "approval-submitted",
    path: "/states/approval-submitted",
    title: "Approval Submitted",
    kind: "success",
    group: "Billing",
    message: "Your approval request has been sent to the reviewer.",
    primaryAction: "View approval queue",
    secondaryAction: "Back to billables",
  },
  {
    id: "invite-accepted",
    path: "/states/invite-accepted",
    title: "Invite Accepted",
    kind: "success",
    group: "Access",
    message: "The team member can now sign in with their firm details.",
    primaryAction: "Go to sign in",
    secondaryAction: "Invite another member",
  },
  {
    id: "password-reset",
    path: "/states/password-reset",
    title: "Password Reset",
    kind: "success",
    group: "Access",
    message: "The password has been updated. Use the new password the next time you sign in.",
    primaryAction: "Sign in",
    secondaryAction: "Back to help",
  },
  {
    id: "storage-unavailable",
    path: "/states/storage-unavailable",
    title: "Storage Unavailable",
    kind: "unavailable",
    group: "Files",
    message: "Document storage is not available right now. Try again before uploading sensitive matter files.",
    primaryAction: "Try storage again",
    secondaryAction: "Back to matter",
  },
  {
    id: "sync-progress",
    path: "/states/sync-progress",
    title: "Sync Progress",
    kind: "loading",
    group: "Integrations",
    message: "Firm records are syncing. Recent changes may appear in a few moments.",
    primaryAction: "View sync details",
    secondaryAction: "Continue working",
    animation: "progress",
    progress: 42,
  },
  {
    id: "no-captured-work",
    path: "/states/no-captured-work",
    title: "No Captured Work",
    kind: "empty",
    group: "Capture",
    message: "No captured work is waiting for review. Start the work meter or connect the extension to begin.",
    primaryAction: "Start work meter",
    secondaryAction: "Set up extension",
  },
  {
    id: "not-configured",
    path: "/states/not-configured",
    title: "Not Configured Yet",
    kind: "unavailable",
    group: "Setup",
    message: "This feature is planned for your workspace but is not configured yet.",
    primaryAction: "View setup steps",
    secondaryAction: "Ask assistant",
  },
];

export const fallbackStateByPath = fallbackStateCatalog.reduce((states, state) => {
  states[state.path] = state;
  return states;
}, {});

export function getFallbackState(path) {
  return fallbackStateByPath[path] || fallbackStateCatalog[0];
}
